services:
  nextjs:
    image: node:20
    container_name: nextjs
    user: node
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    restart: always
    command: sh -c "npm i && npm run dev"

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin123
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
